### ISSUE TITLE
Fix RTD link in README.md

### ISSUE THREAD

**Issue by drreynolds** [LLNL/RAJA-tutorials#6]
The current link for "RAJA User Guide and Tutorial" in `README.md` (https://raja.readthedocs.io/en/master) should be changed to https://raja.readthedocs.io/en/main/

**Comment by rhornung67** [comment]
Thanks @drreynolds This repo hasn't been touched in a while. I'll fix the link.

**Comment by drreynolds** [comment]
Sure thing.  I came across this when looking for RAJA tutorials for part of my parallel computing class, when I noticed the broken link.  I assumed it was a casualty of the recent "master" -> "main" branch renaming over the last couple of years.

**Comment by rhornung67** [comment]
Not to mention that the tutorial material in here needs to be updated in places and extended to cover newer capabilities.

**Comment by rhornung67** [comment]
Fixed link to RAJA user guide. Also, renamed master branch to main.
